import type { Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./global.css"
import SidebarLayout from '@/components/layouts/sidebar-layout';

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}
const localization = {
  signIn: {
    start: {
      title: "Inicia Sesión ",
      subtitle: "Accede a tu área de consultas"
    }
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="es">
        <head>
          <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
            rel="stylesheet"
          />
        </head>
        <body className={` antialiased`}>
         <SidebarLayout>
            {children}
          </SidebarLayout>
        </body>
      </html>
    </ClerkProvider>
  )
}